name: mesa_for_dummies
description: A sample command-line application.
version: 0.1.0
homepage: https://github.com/Igor1201/mesa_for_dummies
author: Igor Borges <igor@borges.me>

executables:
  mesa-for-dummies: main

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  d20: ^0.2.0
  args: ^1.5.0
  http: ^0.11.3+17
  json_annotation: ^1.0.0

dev_dependencies:
  test: ^1.0.0
  build_runner: ^0.10.0
  json_serializable: ^1.0.0
