name: mesa_for_dummies
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Igor Borges <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  d20: ^0.2.0
  http: ^0.11.3+17
  args: ^1.5.0

dev_dependencies:
  test: ^1.0.0
